name: t-dat-902

services:
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: .docker/Dockerfile
    ports:
      - "${API_PORT}:${API_PORT}"
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${API_PORT}`
    volumes:
      - ./api:/app
      - ./api/node_modules:/app/node_modules
    command: sh -c "npm install && npm run dev"
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: .docker/Dockerfile
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${FRONTEND_PORT}
    volumes:
      - ./frontend:/app
      - ./frontend/node_modules:/app/node_modules
    command: sh -c "npm install && npm run dev -- --host"
    depends_on:
      - api

  # Apache Hadoop (ResourceManager, NodeManager, NameNode, DataNode)
  hadoop:
    container_name: hadoop
    image: harisekhon/hadoop:2.9
    restart: always
    environment:
      - SSH_GenerateKey=no # don't generate host keys
    ports:
      - "8042:8042"
      - "8088:8088"
      - "19888:19888"
      - "50070:50070"
      - "50075:50075"

  # Apache Spark
  spark:
    container_name: spark
    image: spark:python3
    restart: unless-stopped
    command: /opt/spark/bin/pyspark
    tty: true
    stdin_open: true
    ports:
      - "4040:4040"

  #volumes:
    #mysql-volume:
    #mongo-volume:
