name: CI Pipeline

on:
  push:
    branches:
      - main  # Déclenche l'action lors d'un push sur la branche principale
  pull_request:
    branches:
      - main  # Déclenche l'action lors de la création d'une pull request

jobs:
  test:
    runs-on: ubuntu-latest  # Utilise un runner Ubuntu pour ton environnement de test

    steps:
      # Etape 1 : Checkout du code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Etape 2 : Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Choisir la version de Python que tu utilises

      # Etape 3 : Installer les dépendances du backend
      - name: Install backend dependencies
        run: |
          cd backend  # Se déplacer dans le dossier backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Installer les dépendances spécifiées dans /backend/requirements.txt

      # Etape 4 : Lancer les tests unitaires
      - name: Run tests with pytest
        run: |
          cd backend  # Se déplacer dans le dossier backend
          pytest --maxfail=1 --disable-warnings -q  # Exécuter les tests unitaires backend
